import { Lock, Star } from 'lucide-react';

interface TierCirclesProps { currentTier: 'Bronze' | 'Silver' | 'Gold' | 'Platinum'; scannedCount: number; onCircleClick: (tier: 'Bronze' | 'Silver' | 'Gold' | 'Platinum', isLocked: boolean) => void; }

const TIER_INFO = { Bronze: { scansRequired: 0, color: '#cd7f32', maxReservations: 1, gradient: 'linear-gradient(135deg, #cd7f32 0%, #a0522d 100%)' }, Silver: { scansRequired: 3, color: '#c0c0c0', maxReservations: 2, gradient: 'linear-gradient(135deg, #c0c0c0 0%, #a8a8a8 100%)' }, Gold: { scansRequired: 6, color: '#ffd700', maxReservations: 3, gradient: 'linear-gradient(135deg, #ffd700 0%, #ffed4e 100%)' }, Platinum: { scansRequired: 9, color: '#e5e4e2', maxReservations: 5, gradient: 'linear-gradient(135deg, #e5e4e2 0%, #d3d3d3 100%)' } };

export function TierCircles({ currentTier, scannedCount, onCircleClick }: TierCirclesProps) {
  const tiers: Array<'Bronze' | 'Silver' | 'Gold' | 'Platinum'> = ['Bronze', 'Silver', 'Gold', 'Platinum'];
  return (<div className="flex flex-row gap-3 items-center justify-center py-4">{tiers.map((tier) => { const info = TIER_INFO[tier]; const isUnlocked = scannedCount >= info.scansRequired; const isCurrent = tier === currentTier; const scansNeeded = Math.max(0, info.scansRequired - scannedCount); return (<button key={tier} onClick={() => onCircleClick(tier, !isUnlocked)} className={`relative transition-all active:scale-95 ${isCurrent ? 'w-20 h-20' : 'w-14 h-14'}`}><div className={`w-full h-full rounded-full flex items-center justify-center transition-all ${isUnlocked ? 'shadow-[0_4px_16px_rgba(0,0,0,0.2)]' : 'opacity-40 grayscale'}`} style={{ background: isUnlocked ? info.gradient : '#d4d4d4' }}>{isUnlocked ? (<div className="flex flex-col items-center justify-center"><Star className={`${isCurrent ? 'w-8 h-8' : 'w-5 h-5'} text-white`} fill="white" />{isCurrent && (<span className="text-[9px] text-white font-bold mt-0.5">{info.maxReservations}</span>)}</div>) : (<Lock className="w-5 h-5 text-white" />)}</div>{isCurrent && (<div className="absolute inset-0 rounded-full animate-ping opacity-30" style={{ background: info.color }} />)}<div className="absolute -bottom-5 left-1/2 transform -translate-x-1/2 whitespace-nowrap"><span className={`text-[10px] font-bold ${isCurrent ? 'text-foreground' : 'text-muted-foreground'}`} style={isCurrent ? { color: info.color } : {}}>{tier}</span></div>{!isUnlocked && scansNeeded > 0 && (<div className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-primary text-white flex items-center justify-center shadow-md"><span className="text-[10px] font-bold">{scansNeeded}</span></div>)}</button>); })}</div>);
}